// SPDX-License-Identifier: LicenseRef-AgentLintel-Free-Use-No-Resale-1.0
"use strict";

const fs = require("node:fs");
const path = require("node:path");
const { readYaml, readJson } = require("./../lib/io");

const V1_DIRS = [".agentlintel", ".ai-governance"];

function findV1(root) {
  for (const dirName of V1_DIRS) {
    const contextPath = path.join(root, dirName, "context.yaml");
    if (fs.existsSync(contextPath))
      return { dir: path.join(root, dirName), name: dirName };
  }
  return null;
}

function isFilled(value) {
  return (
    value != null &&
    typeof value === "string" &&
    value.trim() &&
    !value.includes("<FILL_THIS_IN>")
  );
}

function migrate(root) {
  const report = ["# AgentLintel v1 -> v2 migration report", ""];
  const v1 = findV1(root);
  if (!v1)
    return {
      ok: false,
      log: [
        `ERROR no v1 layout found (looked for ${V1_DIRS.map((dir) => dir + "/context.yaml").join(", ")})`,
      ],
      files: {},
    };

  report.push(
    `Source: \`${v1.name}/\` (v1). Generated by \`agentlintel init --from-v1\`.`,
    "",
  );

  const context = readYaml(path.join(v1.dir, "context.yaml")) || {};
  const facts = [];
  const pendingFact = (id, claim, note) =>
    facts.push({ id, claim, check: { type: "pending", note } });
  const pathFact = (id, claim, factPath) =>
    facts.push({ id, claim, check: { type: "path_exists", path: factPath } });

  const primitives = context.primitives || {};
  if (primitives.result && isFilled(primitives.result.path))
    pathFact(
      "result-primitive",
      `Result lives in ${primitives.result.path} - import it, never redefine it`,
      primitives.result.path,
    );
  if (primitives.execution_context && isFilled(primitives.execution_context.path))
    pathFact(
      "execution-context",
      `ExecutionContext lives in ${primitives.execution_context.path}`,
      primitives.execution_context.path,
    );
  if (context.errors && isFilled(context.errors.catalog_path))
    pathFact(
      "error-catalog",
      `Error catalog lives at ${context.errors.catalog_path}`,
      context.errors.catalog_path,
    );
  if (context.errors && isFilled(context.errors.pattern))
    pendingFact(
      "error-code-grammar",
      `Error codes follow ${context.errors.pattern}`,
      "grammar is enforced by the error-code.format rule; delete this fact once rules.yaml carries your categories",
    );
  if (context.validation && isFilled(context.validation.library))
    pendingFact(
      "validation-library",
      `Boundary validation uses ${context.validation.library}`,
      `derive a file_contains check against your lockfile/csproj for ${context.validation.library}`,
    );
  if (context.project && isFilled(context.project.name))
    pendingFact(
      "project-name",
      `This project is ${context.project.name} (package manager: ${context.project.package_manager || "unknown"})`,
      "informational - keep in AGENTS.md prose instead, or write a check",
    );

  for (const command of (context.verification && context.verification.commands) || []) {
    if (!isFilled(command.command)) continue;
    const commandText = command.command.trim();
    facts.push({
      id: `verify-${command.id || facts.length}`,
      claim: `'${commandText.split("\n")[0]}${commandText.includes("\n") ? " ..." : ""}' passes`,
      check: {
        type: "command",
        run: commandText,
        timeout_ms:
          1000 *
          (command.timeout_seconds || context.verification.timeout_seconds || 120),
      },
    });
  }

  const checkedCount = facts.filter((fact) => fact.check.type !== "pending").length;
  const pendingCount = facts.filter((fact) => fact.check.type === "pending").length;
  report.push(
    "## facts.yaml",
    "",
    `${facts.length} fact(s) generated: ${checkedCount} with machine checks, ${pendingCount} pending (verify warns until you write a check or move the claim to an ADR).`,
    "",
  );

  const exemplars = [];
  for (const exemplar of context.exemplars || [])
    if (isFilled(exemplar.path))
      exemplars.push({
        id: (exemplar.name || path.basename(exemplar.path))
          .toLowerCase()
          .replace(/[^a-z0-9]+/g, "-"),
        shape: exemplar.shape || "crud",
        path: exemplar.path,
        demonstrates:
          exemplar.why || "canonical exemplar (migrated from v1 context.yaml)",
      });

  report.push(
    "## exemplars.yaml",
    "",
    `${exemplars.length} exemplar(s) migrated. verify checks each path exists.`,
    "",
  );

  let guard = null;
  const unmappedKeys = [];
  for (const guardFile of ["guard.json", "architecture.guard.json"]) {
    const guardPath = path.join(v1.dir, guardFile);
    if (!fs.existsSync(guardPath)) continue;

    const v1Guard = readJson(guardPath);
    guard = { version: 2, zones: [], forbidden: [] };
    if (Array.isArray(v1Guard.zones))
      guard.zones = v1Guard.zones.map((zone) => ({
        id: zone.id,
        allow: zone.allow || zone.paths || [],
      }));
    if (Array.isArray(v1Guard.forbidden)) guard.forbidden = v1Guard.forbidden;
    for (const key of Object.keys(v1Guard))
      if (!["version", "zones", "forbidden", "$comment"].includes(key))
        unmappedKeys.push(key);

    report.push(
      "## guard.json",
      "",
      `Migrated from ${guardFile}: ${guard.zones.length} zone(s), ${guard.forbidden.length} forbidden glob(s).`,
    );
    if (unmappedKeys.length)
      report.push(
        "",
        `**Needs manual mapping** (v1 keys with no v2 guard equivalent): ${unmappedKeys.map((key) => `\`${key}\``).join(", ")}.`,
        "- `forbiddenImports`-style regex groups belong in `rules.yaml` as regex rules - each needs pass/fail fixtures (a rule without fixtures fails the gate).",
        "- Policy prose belongs in AGENTS.md principles or an ADR.",
      );
    report.push("");
    break;
  }

  const deadFiles = [
    "index.yaml",
    "modes.yaml",
    "manifest.yaml",
    "slice.manifest.yaml",
    "packs.yaml",
    "features.yaml",
    "orchestrator-policy.yaml",
    "worker-registry.yaml",
    "thinking-modes.yaml",
    "model-routing.yaml",
    "repos.yaml",
    "boot.md",
    "kernel.md",
  ].filter((file) => fs.existsSync(path.join(v1.dir, file)));

  if (deadFiles.length) {
    report.push(
      "## Deleted concepts",
      "",
      "These v1 files have no v2 equivalent (verified, append-only, or deleted - they were neither):",
      "",
    );
    for (const file of deadFiles)
      report.push(
        `- \`${v1.name}/${file}\` - delete after migration; move any surviving intent into an ADR`,
      );
    report.push("");
  }

  const cardsDir = path.join(v1.dir, "cards");
  if (fs.existsSync(cardsDir))
    report.push(
      "## Cards -> Skills",
      "",
      `v1 task cards in \`${v1.name}/cards/\` become standard Agent Skills under \`.agentlintel/skills/<name>/SKILL.md\`.`,
      "The three reference skills (strangler-extraction, mirror-exemplar, audit-architecture) are scaffolded by init; port project-specific cards by hand - most card prose becomes the SKILL.md body unchanged.",
      "",
    );

  report.push(
    "## Next steps",
    "",
    "1. Review pending facts - write a check or move the claim to an ADR.",
    "2. Port forbiddenImports regexes to rules.yaml WITH fixtures.",
    "3. Wire CI: `agentlintel verify --strict` on every PR. A rule that does not run in CI does not exist.",
    "4. Delete the dead v1 files listed above once nothing references them.",
  );

  return {
    ok: true,
    log: [],
    files: {
      ".agentlintel/facts.yaml": factsYaml(facts),
      ".agentlintel/exemplars.yaml": exemplarsYaml(exemplars),
      ...(guard
        ? { ".agentlintel/guard.json": JSON.stringify(guard, null, 2) + "\n" }
        : {}),
      ".agentlintel/MIGRATION.md": report.join("\n") + "\n",
    },
  };
}

function yamlEscape(value) {
  return `"${String(value)
    .replace(/\\/g, "\\\\")
    .replace(/"/g, '\\"')
    .replace(/\n/g, "\\n")
    .replace(/\r/g, "\\r")
    .replace(/\t/g, "\\t")}"`;
}

function factsYaml(facts) {
  const lines = [
    "# Migrated from v1 by `agentlintel init --from-v1`. Every fact needs a passing",
    "# machine check; `pending` facts warn until you write one.",
    "",
    "version: 2",
    "",
    "facts:",
  ];
  for (const fact of facts) {
    lines.push(`  - id: ${fact.id}`);
    lines.push(`    claim: ${yamlEscape(fact.claim)}`);
    const check = fact.check;
    if (check.type === "path_exists")
      lines.push(`    check: { type: path_exists, path: ${yamlEscape(check.path)} }`);
    else if (check.type === "command")
      lines.push(
        `    check: { type: command, run: ${yamlEscape(check.run)}, timeout_ms: ${check.timeout_ms} }`,
      );
    else lines.push(`    check: { type: pending, note: ${yamlEscape(check.note)} }`);
    lines.push("");
  }
  return lines.join("\n");
}

function exemplarsYaml(exemplars) {
  const lines = [
    "# Migrated from v1 context.yaml#exemplars by `agentlintel init --from-v1`.",
    "",
    "version: 2",
    "",
    "exemplars:",
  ];
  if (!exemplars.length) lines[lines.length - 1] = "exemplars: []";
  for (const exemplar of exemplars) {
    lines.push(`  - id: ${exemplar.id}`);
    lines.push(`    shape: ${exemplar.shape}`);
    lines.push(`    path: ${yamlEscape(exemplar.path)}`);
    lines.push(`    demonstrates: ${yamlEscape(exemplar.demonstrates)}`);
    lines.push("");
  }
  return lines.join("\n");
}

module.exports = { migrate, findV1 };
